default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: Jayasree
  password: Jayasree25  # Replace with your MySQL password
  host: localhost

development:
  <<: *default
  database: task_manager_api_development

test:
  <<: *default
  database: task_manager_api_test

production:
  <<: *default
  database: task_management_production

